From ubuntu:16.04
MAINTAINER Hongchuang <hehongchuang@hotmail.com>

# install openssh-server, openjdk and wget
RUN     apt-get update \
     && apt-get install -y openssh-server python-pip python3-pip python ipython ipython-notebook wget curl ssh rsync git vim \
     && pip install --upgrade pip

