version: '3.0'
services:
  dj1:
    build: .
    image: hongchhe/django
    container_name: dj1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    environment:
      - COMPOSE_PROJECT_NAME=spark
    ports:
      - 8000:8000
      - 8018:8018
#    depends_on:
#      - mysql1
    networks:
      - net_hadoop

networks:
  net_hadoop:
    driver: bridge
